model_name: ai-forever/ruBert-base
epochs: 8
num_labels: 10
learning_rate: 2e-5
weight_decay: 0.0
loss_type: bce
focal_gamma: 2.0
pos_weight: null
warmup_steps: 0
scheduler_steps: -1
scheduler_type: "linear_warmup"
