model_name: cointegrated/rubert-tiny2
epochs: 10
num_labels: 10
learning_rate: 5e-5
weight_decay: 0.01
loss_type: bce
pos_weight: null
warmup_steps: 0
scheduler_steps: -1
scheduler_type: "exponential"
activation: sigmoid
