model_name: ai-forever/ruRoberta-large
triton_name: ai-forever-ruRoberta-large
epochs: 10
num_labels: 10
learning_rate: 1e-5
weight_decay: 0.01
loss_type: focal
focal_gamma: 2.0
pos_weight: null
warmup_steps: null
warmup_ratio: 0.15
scheduler_steps: -1
scheduler_type: "linear_warmup"
activation: sigmoid
