dataset_dir: ../data/ru-izard-emotions

save_dir: ./models
checkpoint_dir: ${paths.save_dir}/checkpoints
inference_dir: ./inference_results
save_json: true

triton_model_repository: ./triton_server/model_repository
triton_infer_dir: ./triton_infer_results
onnx_dir: ./onnx_models
tensorrt_dir: ./tensorrt_models
tensorrt_engine: null

triton_repo_onnx: model_repository_onnx
triton_repo_trt: model_repository_trt

logs_dir: ./logs

mlflow_dir: ${hydra:runtime.cwd}/mlflow
mlflow_uri: "http://127.0.0.1:8080"

plots_dir: "./plots"
timestamp: null
