defaults:
  - data: default
  - model: rubert_tiny2
  - train: default
  - paths: default
  - logger: mlflow
  - _self_

triton:
  url: localhost:8000

seed: 42
accelerator: auto
precision: 32
debug: false
